### ISSUE TITLE
Prevent AutoLoading of GoogleMaps Scripts

### ISSUE THREAD

**Issue by vendrix-ds** [google-map-react/google-map-react#966] opened 2020-10-27 18:05 UTC
We are using the google maps api script in other locations in our react app. When this component fires, it re-loads those scripts firing the error "index.js:1 You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors" 

When initializing the component can an option be passed in to prevent the autoload the google maps scripts? 

David

**Comment by patrickdunagan** [comment] 2020-10-30 23:04
I've run into the same issue.  My work around is to check for a loaded script with useEffect on componentDidMount and remove the script.  Then render the new script.

 const removeGoogleMapScript = () => {
        let keywords = ['maps.googleapis'];
    
        window.google = {};
    
        let scripts = document.head.getElementsByTagName("script");
        for (let i = scripts.length - 1; i >= 0; i--) {
            let scriptSource = scripts[i].getAttribute('src');
            if (scriptSource != null) {
                if (keywords.filter(item => scriptSource.includes(item)).length) {
                    scripts[i].remove();
                }
            }
        }
    }

**Comment by itsmichaeldiego** [comment] 2020-11-01 01:53
@vendrix-ds @patrickdunagan Thanks! We're working on it! 

BTW: this is a duplicate of https://github.com/google-map-react/google-map-react/issues/966

**Closed by itsmichaeldiego** 2020-11-01 01:53 UTC

**Comment by itsmichaeldiego** [comment] 2020-11-01 13:19
@vendrix-ds @patrickdunagan Fixed and released in version `2.1.9`, let me know if its working. Thanks in advance!

**Comment by willemodendaal** [comment] 2021-02-12 13:56
This looks good in v2.1.9. At first I thought it did not work, but then realized my externally-loaded gmaps script had not finished initializing by the time I rendered GoogleMapReact, in which case GoogleMapReact rendered its own script tag and I got the error again.
Solved by making sure I don't try to load GoogleMapReact until my other google map script had finished loading.
