### ISSUE TITLE
Next.js SSR error after upgrading to 2.0.2

### ISSUE THREAD

**Issue by sdornan** [google-map-react/google-map-react#901] opened 2020-07-30 16:52 UTC
**Describe the bug 🐛**

An error is returned when rendering a map via the server in Next.js. The error is "Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object." 

Version 1.1.7 works fine, so something broke between then and 2.0.2.

**To Reproduce 🔍**

See https://codesandbox.io/s/sleepy-boyd-r2j78?file=/pages/index.js

**Screenshots 🖥**

<img width="989" alt="image" src="https://user-images.githubusercontent.com/563517/88951113-2f8f5180-d25b-11ea-8cad-4ca0deaf82a9.png">

**Comment by itsmichaeldiego** [comment] 2020-07-30 23:30
Well, it was a big change so I was assuming some problems were going to come our way. Thanks for reporting this. Seems that the issue is only with SSR. I will take a look.

**Comment by itsmichaeldiego** [comment] 2020-07-31 06:13
This has been fixed and released in `2.0.4`, hope there're no further problems!

@sdornan @jspencersharpe @gbwashleybrown

**Closed by itsmichaeldiego** 2020-07-31 06:13 UTC
Labels: help wanted

**Comment by salonee-vc** [comment] 2024-01-29 10:31
@itsmichaeldiego still facing issue in v2.2.1
