### ISSUE TITLE
Children being unmounted immediately after first render

### ISSUE THREAD

**Issue by zuhair-naqvi** [google-map-react/google-map-react#269] opened 2016-11-02 03:35 UTC
GoogleMapReact seems to be unmounting its children after first render. Preventing me from calling setState within a marker when an event occurs eg. If I want the marker to change color when someone checks into that place, the component's unmounted and React throws.

Here's an example of this behaviour:

```
class Marker extends React.Component {
  state = {
    placeClassName: 'place'
  };

  componentDidMount() {
    console.log('Mounted');
  }
  
  componentWillUnmount() {
    console.log('Unmounting');
  }
  
  render() {
    return <div className={this.state.placeClassName} >MyPlace</div>
  }
}

class SimpleMap extends React.Component {
  state = {
    center: [60.938043, 30.337157],
    zoom: 9,
  };


  _onChange = ({center, zoom}) => {
    this.setState({
      center: center,
      zoom: zoom,      
    });
  }
  
  render() {
    return (
       <GoogleMapReact
        onChange={this._onChange}
        center={this.state.center}
        zoom={this.state.zoom}>
        <Marker key="abc" lat={60.955413} lng={30.337844}/>
      </GoogleMapReact>
    );
  }
}


ReactDOM.render(
  <div style={{width: '100%', height: 400}}>
    <SimpleMap/>
  </div>,
  document.getElementById('main')
);

```

prints "Mounted" and "Unmounting" straight after

**Comment by istarkov** [comment] 2016-11-02 09:11
Its by design, until map api is loaded, markers drawn on a top of it in internal div.
Then map is loaded marker drawn inside gmap layer

**Comment by zuhair-naqvi** [comment] 2016-11-03 02:55
So how do you recommend we animate markers on events?

**Comment by MartinDawson** [comment] 2018-09-14 09:50
@zuhair-naqvi What's the actual fix for this? Did you figure it out?

**Comment by itsmichaeldiego** [comment] 2020-09-26 09:58
Closing due to inactivity, feel free to open a new issue if needed

**Closed by itsmichaeldiego** 2020-09-26 09:58 UTC
