### ISSUE TITLE
1.1.3 with react-places-autocomplete - "You have included the Google Maps JavaScript API multiple times on this page."

### ISSUE THREAD

**Issue by blueandhack** [google-map-react/google-map-react#736] opened 2019-04-03 00:46 UTC
Today, I upgrade this package to `1.1.3`, I used `react-places-autocomplete` same time. 

Then I got the error at Chrome's console, `You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.`

But version `1.1.2` does not have the problem, so downgrade to `1.1.2`.

NO other google packages, I just know the problem from `Load the library in your project using google maps library` from `react-places-autocomplete`, but I don't know why `1.1.2` can survive with `react-places-autocomplete`

My environment:
`react-places-autocomplete: 7.2.1`
`react: 16.8.6`
```
 yarn versions v1.15.2
{ yarn:
   '1.15.2',
  node:
   '11.13.0',
  v8:
   '7.0.276.38-node.18',
  uv:
   '1.27.0',
  zlib:
   '1.2.11',
  brotli:
   '1.0.7',
  ares:
   '1.15.0',
  modules:
   '67',
  nghttp2:
   '1.34.0',
  napi:
   '4',
  llhttp:
   '1.1.1',
  http_parser:
   '2.8.0',
  openssl:
   '1.1.1b',
  cldr:
   '34.0',
  icu:
   '63.1',
  tz:
   '2018e',
  unicode:
   '11.0' }
✨  Done in 0.03s.
```

**Comment by itsmichaeldiego** [comment] 2019-04-03 12:46
@blueandhack The problem is with this library and not autocomplete, please rollback to 1.1.2 we're working on a fix

**Comment by itsmichaeldiego** [comment] 2019-04-03 13:29
@blueandhack Just released 1.1.4, let me know if that works!

**Comment by MemoryWrong** [comment] 2019-04-03 22:36
@blueandhack @itsmichaeldiego  Yesterday, encountered the same issue, just rolled back to 1.1.2 everything is working now. 

`		<div className="locationTopSearchBarBlock">
				{/* react places autocomplete plugin */}
					<LocationTopSearchBarBlock />
				</div>
			</div>
			<div className="locationSearchResult pr-0 col-12 col-lg-6 col-xl-5">
				<LocationSearchResult
					carParks={carParks}
					handleActiveCarPark={handleActiveCarPark}
					activeIndex={activeIndex}/>
			</div>
			<div className="mapViewBlock col-12 col-lg-6 col-xl-7 px-0">
				{/* using google-map-react 1.1.2 version, otherwise has multiple API loading issues */}
				<MapViewBlock
					mapData={mapData}
					infoWindowData={activeCarPark}
					carParks={carParks}
					handleClickMarker={handleClickMarker}
					{...mapDefaultProps}/>
			</div>`

And I added `<script src="https://maps.googleapis.com/maps/api/js?...` at the top script loader of the page

**Comment by MemoryWrong** [comment] 2019-04-03 22:39
`<script src="https://maps.googleapis.com/maps/api/js?`

**Comment by itsmichaeldiego** [comment] 2019-04-04 03:51
@MemoryWrong what about 1.1.4?

**Comment by blueandhack** [comment] 2019-04-04 08:36
> @blueandhack Just released 1.1.4, let me know if that works!

Yes, it (`1.1.4`) works on my project now! Thank you!

**Comment by itsmichaeldiego** [comment] 2019-04-04 21:24
@blueandhack Thanks for confirming, I will close the issue, let me know if you have any problem in the future, thanks.

**Comment by lanre-mark** [comment] 2020-05-20 10:22
Hi, I've been using this library for a while but just added `use-places-autocomplete` for my SeacrhBar component and I also started have this error.

Do you think its this library that's causing this or `use-places-autocomplete`. If I use `google-map-react` alone it works and if I use `use-places-autocomplete` alone, it also works.

My environment:
     `use-places-autocomplete: 1.3.5`
      `google-map-react: 1.1.7`
     `react: 16.13.1`

**Comment by vijay-anand-dev** [comment] 2020-10-16 18:50
The exact same bug exists in the current version. Facing the same issue. Version that I'm using is 2.1.7

**Closed** 2020-11-01 01:54 UTC

**Comment by itsmichaeldiego** [comment] 2020-11-01 01:56
Folks! We're working on it: https://github.com/google-map-react/google-map-react/issues/954 f

**Comment by itsmichaeldiego** [comment] 2020-11-01 13:20
Fixed and released in version `2.1.9`, let me know if it's working. Thanks in advance!

CC: @blueandhack @lanre-mark @MemoryWrong  @vijay-anand-dev

**Comment by rojermaharjan** [comment] 2021-11-23 04:57
The issue still persists for me. Even in latest and 2.1.9

**Comment by alexkaduk** [comment] 2022-01-03 15:39
Facing the same issue for version 2.1.10
`
You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.
`

**Comment by AGCakza** [comment] 2023-12-27 11:06
> Facing the same issue for version 2.1.10
> `You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.`

I got the same problem
