### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by Kay2dan** [google-map-react/google-map-react#780] opened 2019-08-23 10:31 UTC
Hi guys, I am posting this here after much troubleshooting and unfortunately, am not clear on what further to do to resolve this. Hence the posting here.

[Here is the link to Stackoverflow question I posted.](https://stackoverflow.com/questions/57624234/getting-google-map-react-library-to-load?noredirect=1#comment101702354_57624234)

In my existing app, I installed [google-map-react][1] library locally and I can see it listed in my `package.json` under `dependencies` & the folder is also present in `node_modules` folder. However, when I reference the component constructor in a file like this:

import GoogleMapReact from "google-map-react";

However, when I run the code, I get the errors:

`Error: Cannot find module 'google-map-react'`

`./src/components/partials/Test.jsx
Module not found: Can't resolve 'google-map-react' in '/usr/local/bab/src/components/partials'`

I noticed the path being referenced in the second error is not correct. Its referring to `/usr/local` when my app is in `~/www/...`

I am not clear on what I am doing wrong. The library is not installed globally and I ran `npm uninstall -g google-map-react` just in case, however, it didn't help either.

I also deleted `package-lock.json` & `node_modules` folder & ran `npm install` again. However, that didn't help either.

    System: Ubuntu 18.04
    Node: v10.15.3
    NPM: 6.4.1

My `package.json` file:

    {
      "name": "my-app",
      "version": "0.1.0",
      "private": true,
      "dependencies": {
        "@babel/polyfill": "^7.2.5",
        "@babel/runtime": "^7.2.0",
        "axios": "^0.18.0",
        "google-map-react": "^1.1.4",
        "moment": "^2.23.0",
        "node-sass": "^4.11.0",
        "prop-types": "^15.6.2",
        "qs": "^6.6.0",
        "react": "^16.8.2",
        "react-compound-slider": "^0.16.3",
        "react-cookie-consent": "^2.1.0",
        "react-dates": "^18.3.1",
        "react-dom": "^16.8.2",
        "react-gtm-module": "^2.0.4",
        "react-moment-proptypes": "^1.6.0",
        "react-redux": "^6.0.1",
        "react-router-dom": "^4.3.1",
        "react-scripts": "^2.1.5",
        "react-scroll": "^1.7.10",
        "react-slick": "^0.23.2",
        "react-sticky": "^6.0.3",
        "react-transition-group": "^2.5.2",
        "redux": "^4.0.1",
        "redux-logger": "^3.0.6",
        "redux-persist": "^5.10.0",
        "redux-thunk": "^2.3.0",
        "reselect": "^4.0.0",
        "slick-carousel": "^1.8.1"
      },
      "scripts": {
        "lint": "./node_modules/.bin/eslint -c .eslintrc.js 'src/**/*.{js,jsx}'",
        "lint:fix": "./node_modules/.bin/eslint --fix -c .eslintrc.js 'src/**/*.{js,jsx}'",
        "start": "npm run lint && react-scripts start",
        "startindocker": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "cypress": "npx cypress run",
        "cypress:open": "npx cypress open",
        "eject": "react-scripts eject"
      },
      "eslintConfig": {
        "extends": "react-app"
      },
      "browserslist": [
        ">0.2%",
        "not dead",
        "not ie <= 11",
        "not op_mini all"
      ],
      "devDependencies": {
        "cypress": "^3.2.0",
        "eslint": "^5.3.0",
        "eslint-config-airbnb": "^17.1.0",
        "eslint-config-prettier": "^5.0.0",
        "eslint-plugin-import": "^2.17.3",
        "eslint-plugin-jsx-a11y": "^6.2.1",
        "eslint-plugin-prettier": "^3.1.0",
        "eslint-plugin-react": "^7.14.1"
      }
    }

  [1]: https://www.npmjs.com/package/google-map-react

**Comment by David-Melo** [comment] 2019-10-03 01:12
Was able to reproduce this on my app

**Comment by itsmichaeldiego** [comment] 2019-10-03 14:03
@Kay2dan Did you find a solution? This is clearly not an issue with this library, because 12.8k people are using it, so I've to close the issue. 

I think you've an issue with your config, you're saying that the error is:

```
Can't resolve 'google-map-react' in '/usr/local/bab/src/components/partials'
```

But why is your app looking for a node_module inside `components/partials`? If it will be an error it should be:

```
Can't resolve 'google-map-react' in node_modules/google-map-react'
```

**Closed by itsmichaeldiego** 2019-10-03 14:03 UTC

**Comment by Oyewale** [comment] 2020-04-28 16:42
> @Kay2dan Did you find a solution? This is clearly not an issue with this library, because 12.8k people are using it, so I've to close the issue.
> 
> I think you've an issue with your config, you're saying that the error is:
> 
> ```
> Can't resolve 'google-map-react' in '/usr/local/bab/src/components/partials'
> ```
> 
> But why is your app looking for a node_module inside `components/partials`? If it will be an error it should be:
> 
> ```
> Can't resolve 'google-map-react' in node_modules/google-map-react'
> ```

Your response is totally bad. Someone is experiencing problem and making all efforts to express himself how frustrated it is to him. If you don't know answer to his issue just simply ignore it.

**Comment by itsmichaeldiego** [comment] 2020-07-21 22:31
I do understand that, what you folks need to understand is that this Github issues are not StackOverflow... 

They are for issues related to the library. If you don't know how to code React or Javascript properly, or even import a npm package, you can't be creating issues in all the libraries you use, that is why we've StackOverflow, where there're more people that can help you out!

We've provided [a library with examples](https://github.com/google-map-react/google-map-react-examples) that you can download and play around with, and it works perfectly.

**Comment by elizad** [comment] 2020-12-07 00:02
same issue

**Comment by elizad** [comment] 2020-12-07 00:07
warning " > google-maps-react@2.0.6" has unmet peer dependency "react@~0.14.8 || ^15.0.0 || ^16.0.0".
warning " > google-maps-react@2.0.6" has unmet peer dependency "react-dom@~0.14.8 || ^15.0.0 || ^16.0.0".
warning " > google-map-react@2.1.9" has unmet peer dependency "react@^16.0.0".
warning " > google-map-react@2.1.9" has unmet peer dependency "react-dom@^16.0.0".
