### ISSUE TITLE
Map panning stops working after sudden resize

### ISSUE THREAD

**Issue by cythrawll** [google-map-react/google-map-react#244] opened 2016-09-19 18:57 UTC
Found while toggling device in chrome.  When toggling panning stops working doing extreme size changes.

To reproduce load the example:

http://istarkov.github.io/google-map-react/map/simple/

open developer tools in chrome.

drag the map around.  Note that it works. hit Ctrl+shift+M note that the panning no longer works.

Hit ctrl+shift+M again. note that panning works again.

Start from the wother way. While in device mode. refresh the sample. note that panning works. Ctrl+shift+M note that panning doesn't work.

**Comment by istarkov** [comment] 2016-09-19 19:03
What is `Ctrl+shift+M` and why I should open dev tools and press that buttons? Is it a standard user behavior? Is it somehow reproducible in real life? Or it is some kind of bug which works only with devtools and some key combinations ;-)
If so what are you want me to do ;-)

**Comment by istarkov** [comment] 2016-09-19 19:12
I just remember an anecdote.

- A) Please destroy bathhouse near my house
- B) Why?
- A) I see naked girls from my window
- B) I tried that but it's not true, i could not see naked girls from you window
- A) It's because they are visible only from the top of cabinet in the room corner.

;-) Not sure it translatable ;-)

**Comment by cythrawll** [comment] 2016-09-20 14:58
ctrl shift m, just changes from device mode to desktop mode, it's an easy way to change your viewport suddenly enough to trigger the bug.  It's not really a dev tools only thing.  It's something that QA teams do and the kind of thing they bug you about.

**Comment by istarkov** [comment] 2016-09-20 15:01
So this is somehow reproducible without devtools?

**Comment by cythrawll** [comment] 2016-09-22 22:23
It should be, because the problem is nothing to do with devtools but the
sudden change in viewport size.

However, I went and moved upstream and found that the problem actually
persists on google maps outside of the react component.  So I should
probably report this upstream.

**Comment by whnunlife** [comment] 2018-02-21 17:15
@cythrawll Let me know if you find anything else out on this, I'm seeing this issue occur as well. Only when changing the browser size quickly.

**Comment by itsmichaeldiego** [comment] 2020-09-10 13:19
Closing this as it seems its a problem with google maps itself and not the library

**Closed by itsmichaeldiego** 2020-09-10 13:19 UTC
