### ISSUE TITLE
Map Component doesn't update when the state change

### ISSUE THREAD

**Issue by SouhaibBenFarhat** [google-map-react/google-map-react#584] opened 2018-05-20 22:16 UTC
Everything is amazing with this module except updating the center, I spent more than 3 hours trying to find a solution for this issue, such a nightmare. can anyone share with a code snippet about updating the center of the map depending on the state.

**Comment by itsmichaeldiego** [comment] 2018-05-20 22:44
@SouhaibBenFarhat It would've been faster if you would've looked through the repo issues. The problem is not about the library but the way you use React. This answer would help https://github.com/google-map-react/google-map-react/issues/546#issuecomment-375789488. Let me know if that works.

**Comment by BillGatesNephew** [comment] 2018-05-22 23:31
I'm having the same issue with the center despite trying most the solutions mentioned in other threads. I'm updating the state (a center object) of the parent component of the map via a callback passed to a different child of the parent. The parent then passes the new state to the child map as a prop. However, i'm not seeing any changes at all in the map even though I clearly can see the child map getting the correct values for center.

**Comment by BillGatesNephew** [comment] 2018-05-23 01:01
Update:
For anyone still have issue despite following the steps in #546 to solve the problem. You might want to ensure your packages are up to date. I was able to fix the problem by updating both Node as well as yarn. Hope this helps!

**Comment by itsmichaeldiego** [comment] 2018-05-23 21:05
Great you found your problem @BillGatesNephew !

**Comment by itsmichaeldiego** [comment] 2018-05-23 21:05
Closing the issue as for now.

**Closed by itsmichaeldiego** 2018-05-23 21:05 UTC

**Comment by SouhaibBenFarhat** [comment] 2018-05-23 21:15
you can close the issue anyway, I tried all the existing solutions that you already mentioned but i'm pretty sure that I can use another module which is react-google-maps, he provide a more easier and faster way to interact with the map. if you want to make our life easier please try to improve the way you update the center with your map. the fact that I can drop different components inside the map is really amazing but I can't spent hours trying just to update such minor thing like the default center.

Thank you and keep going.
