### ISSUE TITLE
Generated child component not capturing click

### ISSUE THREAD

**Issue by mikeriley131** [google-map-react/google-map-react#502] opened 2018-01-25 19:21 UTC
(I searched but couldn't find a similar issue.)

I'm generating "pins" via React components on load. When I click on a pin, it opens a "tooltip" (another React component) with details about the location. If I click anywhere on that tooltip other than where the pin is below it (z-index), it triggers a click on the tooltip component, but also on the map, which calls an event I don't want when the tooltip is open. A click on the initial pin component does not trigger the map click event, only the tooltip.

Any ideas why this might be? Please let me know if I need to provide code or further details.

**Comment by itsmichaeldiego** [comment] 2018-01-25 20:28
@mikeriley131 Thanks for opening the issue.

Please do provide code. I believe the problem you're facing can be fixed with a simple `ev.preventDefault()` but as I don't know the code exactly that might not be the case.

**Comment by mikeriley131** [comment] 2018-01-25 20:41
@itsmichaeldiego Yeah, I tried a `preventDefault()` but it had no effect. Here's some code...

The "pin" component
```
const Container = (props) => {
...
  return (
    <Wrapper selected={selected}>
      <Avatar
        selected={selected}
        disabled={disabled}
        onClick={() => selected ? closeSnapshot(id) : openSnapshot(id)}
      >
        {selected ? <Snapshot text={text} address={address} low={low} high={high} open={openAssets} /> : locationAssetCount}
      </Avatar>
    </Wrapper>
  )
}
```

Snapshot is the "tooltip"
```
const Snapshot = ({text, address, low, high, selected, open}) => (
  <Button selected={selected} raised onClick={open}>
    <div>
      <Typography type='body1' align='right'>
        {text}<br />
        <Small>${low}-${high} daily</Small><br />
      </Typography>
      <Typography type='caption' align='right'>
        <Small>{address}</Small><br />
      </Typography>
    </div>
    <NavigateNextIcon />
  </Button>
)
```

That `open` function gets fired on click of the Snapshot, but if you click on an area of the Snapshot that has the map below it instead of one of the pins, a click event I have on the map gets fired.

Let me know if any further details are required.

**Comment by itsmichaeldiego** [comment] 2018-02-08 01:08
@mikeriley131 Did you try using z-index or setting a position absolute to the component that you want to be clickable?

**Comment by mikeriley131** [comment] 2018-02-08 03:55
@itsmichaeldiego Yes, the component is currently absolutely positioned and has a z-index.

**Comment by walidvb** [comment] 2018-02-08 12:51
I'm having a similar issue, where i render 2 marker lists: `dot`s and `scale`s. although my `scale`s are rendered below my `dot`s. I have a feeling that the click is not attached to the child, but rather to the map itself, which then computes the distance. could that be?
<img width="399" alt="screen shot 2018-02-08 at 10 39 01" src="https://user-images.githubusercontent.com/810604/35973435-925825e2-0cbc-11e8-88dc-b6c4c38ba85b.png">

**Comment by itsmichaeldiego** [comment] 2018-02-09 23:09
@walidvb It is a valid point, yes, we need to figure this out soon! I believe there should be an easy way but haven't had spare time to look at this yet, if one of you guys want to debug it and check that would be amazing.

**Comment by stephenfarrar** [comment] 2018-03-14 21:03
If you want to suppress map "click"s, you can add listeners on your component that call `e.stopPropagation()`. You'll need to do this for `click`, `mousedown`, `touchstart`, and `pointerdown`.

**Comment by walidvb** [comment] 2018-03-15 18:19
thanks @stephenfarrar, i chose to attach the event to both children, rather than to suppress the click. For my usecase, i think that would simply silent the click entirely

**Comment by kpennell** [comment] 2018-12-04 18:36
@walidvb @mikeriley131 How did you solve this? Can you please share code?

**Comment by mikeriley131** [comment] 2018-12-04 21:22
@kpennell I don't believe we ever did, bur our designs/functionality have since changed so it's no longer an issue. Sorry I can't be of more help.

**Comment by kpennell** [comment] 2018-12-05 02:36
@mikeriley131 Darn, thanks for the response.

**Comment by kpennell** [comment] 2018-12-05 02:36
@mikeriley131 Darn, thanks for the response.

**Comment by walidvb** [comment] 2018-12-05 15:33
Hi @kpennell my solution was to add `pointer-events: none;` to the markers, which worked fine for my usecase.

**Comment by itsmichaeldiego** [comment] 2018-12-05 15:46
Sorry, [before I gave a bad answer](https://github.com/google-map-react/google-map-react/issues/502#issuecomment-360590334), using `event.stopPropagation()` should fix the issue as it does in general as @stephenfarrar [pointed out](https://github.com/google-map-react/google-map-react/issues/502#issuecomment-373174107)

**Comment by kpennell** [comment] 2018-12-05 16:07
event.stopPropagation on the parent onClick?

**Comment by kpennell** [comment] 2018-12-05 16:32
Aha, makes sense. Stop it from going down to the parent.

Good ol web dev 102...forgot all the bubbling and capturing stuff. Or was
quite rusty on it

**Comment by itsmichaeldiego** [comment] 2018-12-05 17:00
@kpennell No prob, let me know if that works!

**Comment by VictorKolb** [comment] 2018-12-12 10:18
@itsmichaeldiego yes, it works! thank you

**Comment by itsmichaeldiego** [comment] 2018-12-12 11:56
@VictorKolb Happy to hear that!

**Comment by itsmichaeldiego** [comment] 2018-12-12 11:57
@kpennell let me know if @stephenfarrar's [answer](https://github.com/google-map-react/google-map-react/issues/502#issuecomment-373174107) worked

**Comment by bertya** [comment] 2019-01-31 23:37
@itsmichaeldiego Hey man, I have event.stopPropagation() on my component, but when there is a for example, subway station overlapped, when I click my marker, the stations's infowindow get opened still.

**Comment by itsmichaeldiego** [comment] 2020-09-03 01:20
Duplicate of https://github.com/google-map-react/google-map-react/issues/508. Keeping that one as it is more detailed

**Closed by itsmichaeldiego** 2020-09-03 01:20 UTC

**Comment by spyshower** [comment] 2021-01-07 15:32
I managed to solve this with `onClick={(e) => e.stopPropagation()}`, however double clicking still zooms the map. Any thoughts on this one?

**Comment by walidvb** [comment] 2021-01-07 15:34
@spyshower  `onDoubleClick` ?

**Comment by spyshower** [comment] 2021-01-07 16:04
> @spyshower `onDoubleClick` ?

Yea... didn't work :P

**Comment by stephenfarrar** [comment] 2021-01-07 22:06
If you don't need double-click zoom at all, you can use https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.disableDoubleClickZoom

If you only want to suppress double-click zoom on your component, did you try `stopPropagation` on `mousedown` and `pointerdown`? See https://github.com/google-map-react/google-map-react/issues/502#issuecomment-373174107

**Comment by spyshower** [comment] 2021-01-08 09:51
@stephenfarrar I have seen your comment but I am not sure how to do that. Could you share your code for that? Plus, I would like to keep double click for zoom.

**Comment by illing2005** [comment] 2021-04-22 11:27
> @itsmichaeldiego Hey man, I have event.stopPropagation() on my component, but when there is a for example, subway station overlapped, when I click my marker, the stations's infowindow get opened still.

@bertya , I'm having the same issue.
Did you find a solution?
