### ISSUE TITLE
Clicking on Pin Fires Off Parent Map OnClick Event

### ISSUE THREAD

**Issue by amber-cd** [google-map-react/google-map-react#781] opened 2019-08-26 15:42 UTC
We have need for all three of the following in our map:

1. Custom marker pins with their own appearance + on click events
2. Polygon areas
3. Map click events, which use the lat and long of the user's click location.

The implementation:
1. Make a map pin component with an `onClick` prop; run that `onClick`
2. In `render`, in `onGoogleApiLoaded`, use `map.addListener('click', this.onMapClick);` to bind the `onClick` event (and also add the polygons here, at least for now)

The problem: We want to set the map up such that the map click event will fire _only_ if the user clicks on the 'background' map; we want to skip it if the user clicks on a pin and run only the pin `onClick` event.

However, that doesn't seem to work, and I can't seem to find a solution. The `click` event for the map seems to fire off _before_ the `onClick` handler for the pin, which means that I can't just use `event.stopPropagation` in the pin's `onClick` handler. Likewise, the event handled by `onMapClick` does not seem to have target information corresponding to the `pin`, so I can't just look at `e.ra.target` to figure out if it was a pin click or not.

Has anyone encountered a similar use case? How did you resolve it? I see a few similar use cases from searching around the issues list, but nothing which has been similar enough to this scenario to provide a solution. Am I binding the map click event in the wrong fashion or something?

**Comment by corys** [comment] 2019-10-01 01:38
Also encountered this.  Have not figured out a solution yet.

**Comment by amber-cd** [comment] 2019-10-02 14:45
Please let me know if you figure it out; I've been fairly stumped on this issue, myself. I'll post here if I find anything, though.

**Comment by Ronin11** [comment] 2020-02-06 17:40
+1

**Comment by itsmichaeldiego** [comment] 2020-02-11 20:39
@amber-cd @Ronin11 @corys I think this is a duplicate of https://github.com/google-map-react/google-map-react/issues/508 right?

**Comment by karldanninger** [comment] 2020-04-08 15:22
I just dealt with this, you can use `preventMapHitsAndGesturesFrom` to stop click propagation to the map.
https://developers.google.com/maps/documentation/javascript/reference/overlay-view#OverlayView.preventMapHitsAndGesturesFrom

#855

**Closed** 2020-07-22 22:27 UTC
