### ISSUE TITLE
Position Marker not center on page when zoomOut

### ISSUE THREAD

**Issue by btbensoft** [google-map-react/google-map-react#618] opened 2018-07-20 13:55 UTC
Hello,

I'm gonna try to explain my problem.

When you are zoomOut you can see more that 1 map on the screen (i.e. see bellow google version).

Google fixes the markers position in the center of the displayed plans :

![image](https://user-images.githubusercontent.com/36570423/43005520-6b9bdc90-8c33-11e8-87bc-ffd320095fcc.png)

When i use **google-map-react** you set markers on the right maps display. Example 

![image](https://user-images.githubusercontent.com/36570423/43005914-8b383034-8c34-11e8-891a-a6c3948c964e.png)

how can you set the markers position calcul on the center maps display as Google? [google maps example](https://developers.google.com/maps/documentation/javascript/examples/marker-simple)

I hope you understand my issue.

I can help you to fixe it but i need your help to identify the positions calcul

Thanks 

Ben

**Comment by itsmichaeldiego** [comment] 2018-07-22 11:58
@btbensoft Hello Ben, this is a known problem for us, and there is an issue already about it #544. 

Let me explain you a little bit, the problem is that we calculate the position of 1 marker on the map, when you zoom out like this, as you clearly stated, there are 2 or more maps, so that means that we will need to render 2 markers. 

Currently we don't support this, and I am not sure we will prioritize this any time soon, but of course, if you want to help, I am happy to help you to achieve this! 

I will close the issue, as I said its a duplicate of #544

**Closed by itsmichaeldiego** 2018-07-22 11:58 UTC
